apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pydjangoapps.pepedocs.org
spec:
  scope: Namespaced
  group: pepedocs.org
  names:
    kind: PyDjangoApp
    plural: pydjangoapps
    singular: pydjangoapp
    shortNames:
      - pydjangoapps
      - pydjangoapp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
                djangoSpec:
                  type: object
                  properties:
                    managePyPath:
                      type: string
                    port:
                      type: integer
                    host:
                      type: string
  scope: Namespaced